[env:devkit-mpc5744p]
platform = symlink://../..
board = devkit-mpc5744p
framework = baremetal
; EWL is inside the downloaded toolchain package (e200_ewl2 next to gcc).
board_build.ewl_dir = ${platformio.packages_dir}/toolchain-powerpc-eabivle/e200_ewl2
